---
<% confset = { ipaddress: "zerohost", name: "127.0.0.1" } %>
settings:
  command_base: /usr/local/bin/knife

commands:
<% confset.each_pair do |target, node| %>
  - name: boot_<%= target %>
    command: zero bootstrap 127.0.0.1
    condition:
    options:
      node-name: <%= node %>
      ssh-user: docker
      ssh-password: docker
      sudo:
      verbose:
  - name: converge_<%= target %>
    command: zero converge
    condition: 'name:<%= node %>'
    options:
      attribute: knife_zero.host
      override-runlist: 'kzi::default'
      ssh-user: docker
      ssh-password: docker
      sudo:
      verbose:
  - name: converge2_<%= target %>
    command: zero converge --client-version latest
    condition: 'name:<%= node %>'
    options:
      attribute: knife_zero.host
      override-runlist: 'kzi::default'
      ssh-user: docker
      ssh-password: docker
      sudo:
      verbose:
<% end %>
